<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist
PUBLIC '-//Apple//DTD PLIST 1.0//EN'
'http://www.apple.com/DTDs/PropertyList-1.0.dtd'>
<plist>
	<dict>
		<key>fileTypes</key>
		<array>
			<string>tlv</string>
			<string>TLV</string>
		</array>
		<key>foldingStartMarker</key>
		<string>(begin)\s*(//.*)?$</string>
		<key>foldingStopMarker</key>
		<string>^\s*(begin)$</string>
		<key>name</key>
		<string>TL Verilog</string>
		<key>patterns</key>
		<array>
			<dict>
				<key>match</key>
				<string>\b(automatic|cell|config|deassign|defparam|design|disable|edge|endconfig|endgenerate|endspecify|endtable|endtask|event|generate|genvar|ifnone|incdir|instance|liblist|library|localparam|macromodule|negedge|noshowcancelled|posedge|pulsestyle_onevent|pulsestyle_ondetect|real|realtime|scalared|showcancelled|specify|specparam|table|task|time|use|vectored|new)\b</string>
				<key>name</key>
				<string>keyword.other.tlverilog</string>
			</dict>
			<!-- Embedded JavaScript inside \viz_js blocks -->
			<dict>
			<key>begin</key>
			<string>^\s*\\viz_js\b.*$</string>

			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
				<key>name</key>
				<string>keyword.control.vizjs.tlverilog</string>
				</dict>
			</dict>

			<!-- Heuristic end: next TLV structural line -->
			<key>end</key>
			<string>^(?=\s*\\(TLV|SV|SV_plus|viz_js)\b|\s*\|pipe|\s*@)</string>

			<key>name</key>
			<string>meta.embedded.block.javascript.tlverilog</string>

			<key>patterns</key>
			<array>
				<dict>
				<key>include</key>
				<string>source.js</string>
				</dict>
			</array>
			</dict>
			<!-- Updated: stages: @1, @-2, @0 (added negative support) -->
			<dict>
				<key>match</key>
				<string>@-?\d+</string>
				<key>name</key>
				<string>entity.name.label.tlverilog</string>
			</dict>
			<!-- Updated: pipes: |pipe (fixed regex for starting with letter/underscore) -->
			<dict>
				<key>match</key>
				<string>\|[a-zA-Z_][a-zA-Z0-9_]*</string>
				<key>name</key>
				<string>entity.name.tag.tlverilog</string>
			</dict>
			<dict>
				<!-- tabs: \t -->
				<key>match</key>
				<string>\t</string>
				<key>name</key>
				<string>invalid.illegal.tlverilog</string>
			</dict>
			<!-- Updated: Behavioral hierarchy: >start (fixed regex, added range support) -->
			<dict>
				<key>match</key>
				<string>&gt;[a-zA-Z_][a-zA-Z0-9_]*(\[[^\]]+\])?</string>
				<key>name</key>
				<string>entity.name.type.tlverilog</string>
			</dict>
			<!-- Updated: Behavioral hierarchy: /start (fixed regex, added range support) -->
			<dict>
				<key>match</key>
				<string>/[a-zA-Z_][a-zA-Z0-9_]*(\[[^\]]+\])?</string>
				<key>name</key>
				<string>entity.name.type.tlverilog</string>
			</dict>
			<dict>
				<!-- Updated: When condition: ?$lol | ?*lol (standard scope) -->
				<key>match</key>
				<string>\?[\$\*][a-zA-Z0-9_]+</string>
				<key>name</key>
				<string>keyword.control.tlverilog</string>
			</dict>
			<!-- Updated: System signal: $sig1 (added $$ support, standard scope) -->
			<dict>
				<key>match</key>
				<string>\${1,2}[a-zA-Z_][a-zA-Z0-9_]*</string>
				<key>name</key>
				<string>variable.other.tlverilog</string>
			</dict>
			<!-- Updated: Alignment (combined % and << etc., added next support) -->
			<dict>
				<key>match</key>
				<string>(&lt;&lt;|&lt;&gt;|&gt;&gt;-?)(\d+|[a-zA-Z_]\w*)|%([+-]\d+|next|[a-zA-Z_]\w*)</string>
				<key>name</key>
				<string>keyword.operator.alignment.tlverilog</string>
			</dict>
			<!-- Updated: M4 macro (added underscore support) -->
			<dict>
				<key>match</key>
				<string>\b[mM]4[+_][a-zA-Z_][a-zA-Z0-9_]*</string>
				<key>name</key>
				<string>support.function.macro.tlverilog</string>
			</dict>
			<!-- M5 macros: m5_foo, m5+fib, m5_bar (no parens), m5_makerchip_module -->
			<dict>
				<key>match</key>
				<string>\bm5([_+][a-zA-Z_][a-zA-Z0-9_]*|\b_makerchip_module)\b</string>
				<key>name</key>
				<string>support.function.macro.tlverilog</string>
			</dict>
			<!-- M5 macro with args start: m5_foo( or m5+fib(  (single-line opening only) -->
			<dict>
				<key>begin</key>
				<string>\b(m5([_+][a-zA-Z_][a-zA-Z0-9_]*|\b_makerchip_module))\s*\(</string>
				<key>beginCaptures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>support.function.macro.tlverilog</string>
					</dict>
					<key>0</key>  <!-- the ( itself -->
					<dict>
						<key>name</key>
						<string>punctuation.section.group.begin.tlverilog</string>
					</dict>
				</dict>
				<key>end</key>
				<string>\)</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.section.group.end.tlverilog</string>
					</dict>
				</dict>
				<key>name</key>
				<string>meta.macro-call.tlverilog</string>
				<key>patterns</key>
				<array>
					<!-- You can later add comma, string, etc. patterns inside args here -->
					<dict>
						<key>include</key>
						<string>#strings</string>
					</dict>
					<dict>
						<key>match</key>
						<string>,</string>
						<key>name</key>
						<string>punctuation.separator.arguments.tlverilog</string>
					</dict>
				</array>
			</dict>
			<dict>
				<key>match</key>
				<string>\buse\s*\(\s*['"]?m5[-.\d]+['"]?\s*\)</string>
				<key>name</key>
				<string>keyword.control.import.tlverilog</string>
			</dict>
			<!-- Updated: Regions (expanded to full list from doc) -->
			<dict>
				<key>match</key>
				<string>^\\(TLV|TLVHDL|TLC|SV|SV_plus|VHDL|VHDL_plus|C|C_plus|M5)(\s|$)</string>
				<key>name</key>
				<string>keyword.control.region.tlverilog</string>
			</dict>
			<!-- Updated: SV signal (added ** support, standard scope) -->
			<dict>
				<key>match</key>
				<string>\*{1,2}[a-zA-Z_][a-zA-Z0-9_]*</string>
				<key>name</key>
				<string>variable.other.tlverilog</string>
			</dict>
			<!-- Updated: Constant (removed extra \b for #word) -->
			<dict>
				<key>match</key>
				<string>#[a-zA-Z_][a-zA-Z0-9_]*</string>
				<key>name</key>
				<string>constant.other.tlverilog</string>
			</dict>
			<!-- New: Physical hierarchy: -hierarchy or ->hierarchy -->
			<dict>
				<key>match</key>
				<string>-&gt;?[a-zA-Z_][a-zA-Z0-9_]*</string>
				<key>name</key>
				<string>entity.name.type.physical.tlverilog</string>
			</dict>
			<!-- New: Attributes: ^attr, ^^attr -->
			<dict>
				<key>match</key>
				<string>\^{1,2}[a-zA-Z_][a-zA-Z0-9_]*</string>
				<key>name</key>
				<string>entity.other.attribute-name.tlverilog</string>
			</dict>
			<!-- New: Invalid line type character (first non-space char in TL-X region, approx. flat
			match) -->
			<dict>
				<key>match</key>
				<string>^[^ \\\t\n]</string>
				<key>name</key>
				<string>invalid.illegal.line-type.tlverilog</string>
			</dict>
			<!-- New: File format version line -->
			<dict>
				<key>match</key>
				<string>^\\(m4_)?TLV_version\s+[\d.]+:.*$</string>
				<key>name</key>
				<string>keyword.control.version.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>^\\(m5_)?TLV_version\s+[\w.]+:.*$</string>
				<key>name</key>
				<string>keyword.control.version.tlverilog</string>
			</dict>
			<!-- New: M4 variables -->
			<dict>
				<key>match</key>
				<string>\bM4_[A-Z_][A-Z0-9_]*</string>
				<key>name</key>
				<string>variable.other.constant.m4.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(#|@|begin|end|fork|join|join_any|join_none|forkjoin|{|})\b</string>
				<key>name</key>
				<string>keyword.other.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(initial|always|wait|force|release|assign|always_comb|always_ff|always_latch|forever|repeat|while|for|if|iff|else|case|casex|casez|default|endcase|return|break|continue|do|foreach|randomize|with|inside|dist|clocking|cover|coverpoint|property|bins|binsof|illegal_bins|ignore_bins|randcase|modport|matches|solve|static|assert|assume|before|expect|bind|extends|sequence|var|cross|ref|first_match|srandom|time|struct|packed|final|chandle|alias|tagged|extern|throughout|timeprecision|timeunit|priority|type|union|unique|uwire|wait_order|triggered|randsequence|import|export|context|pure|intersect|wildcard|within|virtual|local|const|typedef|enum|protected|this|super|endmodule|endfunction|endprimitive|endclass|endpackage|endsequence|endprogram|endclocking|endproperty|endgroup|endinterface)\b</string>
				<key>name</key>
				<string>keyword.control.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(std)\b::</string>
				<key>name</key>
				<string>support.class.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\.(atob|atohex|atoi|atooct|atoreal|bintoa|hextoa|itoa|octtoa|realtoa|len|getc|putc|toupper|tolower|compare|icompare|substr|num|exists|first|last|name|index|find|find_first|find_last|find_index|find_first_index|find_last_index|min|max|unique|unique_index|sort|rsort|shuffle|reverse|sum|product|xor|status|kill|self|await|suspend|resume|get|put|peek|try_get|try_peek|try_put|data|eq|neq|next|prev|new|size|delete|empty|pop_front|pop_back|front|back|insert|insert_range|erase|erase_range|set|swap|clear|purge|start|finish)\b</string>
				<key>name</key>
				<string>support.function.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(get_randstate|set_randstate)\b</string>
				<key>name</key>
				<string>support.function.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>\b(null|void)\b</string>
				<key>name</key>
				<string>support.constant.tlverilog</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>keyword.other.tlverilog</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.include.tlverilog</string>
					</dict>
				</dict>
				<key>match</key>
				<string>^\s*(`include)\s+(["&lt;].*["&gt;])</string>
				<key>name</key>
				<string>meta.include.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>`(celldefine|default_nettype|define|else|elsif|endcelldefine|endif|ifdef|ifndef|include|line|nounconnected_drive|resetall|timescale|unconnected_drive|undef|begin_\w+|end_\w+|remove_\w+|restore_\w+)\b</string>
				<key>name</key>
				<string>constant.other.preprocessor.tlverilog</string>
			</dict>
			<!--<dict>
				<key>match</key>
				<string>`\b([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
				<key>name</key>
				<string>constant.other.define.tlverilog</string>
			</dict>-->
			<dict>
				<key>include</key>
				<string>#comments</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.type.tlverilog</string>
					</dict>
					<key>3</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.class.tlverilog</string>
					</dict>
				</dict>
				<key>match</key>
				<string>\b(function)\b\s+(\[.*\])?\s+\b([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
				<key>name</key>
				<string>meta.definition.tlverilog</string>
			</dict>
			<dict>
				<key>captures</key>
				<dict>
					<key>1</key>
					<dict>
						<key>name</key>
						<string>storage.type.tlverilog</string>
					</dict>
					<key>2</key>
					<dict>
						<key>name</key>
						<string>entity.name.type.class.tlverilog</string>
					</dict>
				</dict>
				<key>match</key>
				<string>^\s*(module|function|primitive|class|package|constraint|interface|covergroup|program)\s+\b([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
				<key>name</key>
				<string>meta.definition.tlverilog</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#all-types</string>
			</dict>
			<!--<dict>
				<key>match</key>
				<string>(==|===|!=|!==|&lt;=|&gt;=|&lt;|&gt;)</string>
				<key>name</key>
				<string>keyword.operator.comparison.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(\-|\+|\*|\/|%)</string>
				<key>name</key>
				<string>keyword.operator.arithmetic.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(!|&amp;&amp;|\|\||\bor\b)</string>
				<key>name</key>
				<string>keyword.operator.logical.tlverilog</string>
			</dict>-->
			<!--<dict>
				<key>match</key>
				<string>(&amp;|\||\^|~|{|}|&lt;&lt;|&gt;&gt;|\?|:)</string>
				<key>name</key>
				<string>keyword.operator.bitwise.tlverilog</string>
			</dict>-->
			<dict>
				<key>match</key>
				<string>'\s*\(.+\)</string>
				<key>name</key>
				<string>keyword.operator.staticcasting.tlverilog</string>
			</dict>
	<!-- M5 quoted strings with nesting support -->
	<dict>
		<key>begin</key>
		<string>\['</string>
		<key>beginCaptures</key>
		<dict>
			<key>0</key>
			<dict>
				<key>name</key>
				<string>punctuation.definition.string.begin.m5.tlverilog</string>
			</dict>
		</dict>
		<key>end</key>
		<string>'\]</string>
		<key>endCaptures</key>
		<dict>
			<key>0</key>
			<dict>
				<key>name</key>
				<string>punctuation.definition.string.end.m5.tlverilog</string>
			</dict>
		</dict>
		<key>name</key>
		<string>string.quoted.m5.tlverilog</string>
		<key>contentName</key>
		<string>meta.m5string.content.tlverilog</string>
		
		<!-- CRITICAL: Check patterns before end -->
		<key>applyEndPatternLast</key>
		<integer>1</integer>
		
		<key>patterns</key>
		<array>
			<!-- Match nested strings BEFORE checking for end -->
			<dict>
				<key>begin</key>
				<string>\['</string>
				<key>beginCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.begin.m5.nested.tlverilog</string>
					</dict>
				</dict>
				<key>end</key>
				<string>'\]</string>
				<key>endCaptures</key>
				<dict>
					<key>0</key>
					<dict>
						<key>name</key>
						<string>punctuation.definition.string.end.m5.nested.tlverilog</string>
					</dict>
				</dict>
				<key>name</key>
				<string>string.quoted.m5.nested.tlverilog</string>
				
				<!-- ALSO add this to nested pattern -->
				<key>applyEndPatternLast</key>
				<integer>1</integer>
				
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#m5-nested-string</string>
					</dict>
				</array>
			</dict>
		</array>
	</dict>

    <!-- 2. Then your unpacked array assignment -->
    <dict>
        <key>begin</key>
        <string>'{</string>
        <key>beginCaptures</key>
        <dict>
            <key>0</key>
            <dict>
                <key>name</key>
                <string>keyword.operator.unpackaedarrayassignment.begin.tlverilog</string>
            </dict>
        </dict>
        <key>end</key>
        <string>}</string>
        <key>endCaptures</key>
        <dict>
            <key>0</key>
            <dict>
                <key>name</key>
                <string>keyword.operator.unpackaedarrayassignment.end.tlverilog</string>
            </dict>
        </dict>
        <key>name</key>
        <string>keyword.operator.unpackedarrayassignment.tlverilog</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>match</key>
                <string>.</string>
                <key>name</key>
                <string>constant.character.escape.tlverilog</string>
            </dict>
        </array>
    </dict>
			<dict>
				<key>match</key>
				<string>\b(output|input|inout|and|nand|nor|or|xor|xnor|buf|not|bufif[01]|notif[01]|r?[npc]mos|tran|r?tranif[01]|pullup|pulldown)\b</string>
				<key>name</key>
				<string>support.type.tlverilog</string>
			</dict>
			<dict>
				<key>match</key>
				<string>(\b\d+)?'[sS]?([bB]\s*[0-1_xXzZ?]+|[oO]\s*[0-7_xXzZ?]+|[dD]\s*[0-9_xXzZ?]+|[hH]\s*[0-9a-fA-F_xXzZ?]+|[0-1xz])((e|E)(\+|-)?[0-9]+)?\b</string>
				<key>name</key>
				<string>constant.numeric.tlverilog</string>
			</dict>
			<dict>
				<key>include</key>
				<string>#strings</string>
			</dict>
			<!--<dict>
				<key>match</key>
				<string>\$\b([a-zA-Z_][a-zA-Z0-9_]*)\b</string>
				<key>name</key>
				<string>support.function.tlverilog</string>
			</dict>-->
			<!--<dict>
				<key>match</key>
				<string>\b([A-Z][A-Z0-9_]+)\b</string>
				<key>name</key>
				<string>constant.other.tlverilog</string>
			</dict>-->
		</array>
		<key>repository</key>
		<dict>
			<key>m5-nested-string</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>\['</string>
						<key>end</key>
						<string>'\]</string>
						<key>name</key>
						<string>string.quoted.m5.nested.tlverilog</string>
						
						<!-- Add this here too -->
						<key>applyEndPatternLast</key>
						<integer>1</integer>
						
						<key>patterns</key>
						<array>
							<dict>
								<key>include</key>
								<string>#m5-nested-string</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
			<key>all-types</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>include</key>
						<string>#storage-type-tlverilog</string>
					</dict>
					<dict>
						<key>include</key>
						<string>#storage-modifier-tlverilog</string>
					</dict>
				</array>
			</dict>
			<key>comments</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>/\*</string>
						<key>captures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.comment.tlverilog</string>
							</dict>
						</dict>
						<key>end</key>
						<string>\*/</string>
						<key>name</key>
						<string>comment.block.tlverilog</string>
					</dict>
					<dict>
						<key>captures</key>
						<dict>
							<key>1</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.comment.tlverilog</string>
							</dict>
						</dict>
						<key>match</key>
						<string>(//).*$\n?</string>
						<key>name</key>
						<string>comment.line.double-slash.tlverilog</string>
					</dict>
				</array>
			</dict>
			<key>storage-type-tlverilog</key>
			<dict>
				<key>match</key>
				<string>\b(wire|tri|tri[01]|supply[01]|wand|triand|wor|trior|trireg|reg|parameter|integer|rand|randc|int|longint|shortint|logic|bit|byte|shortreal|string)\b</string>
				<key>name</key>
				<string>storage.type.tlverilog</string>
			</dict>
			<key>storage-modifier-tlverilog</key>
			<dict>
				<key>match</key>
				<string>\b(signed|unsigned|small|medium|large|supply[01]|strong[01]|pull[01]|weak[01]|highz[01])\b</string>
				<key>name</key>
				<string>storage.modifier.tlverilog</string>
			</dict>
			<key>strings</key>
			<dict>
				<key>patterns</key>
				<array>
					<dict>
						<key>begin</key>
						<string>"</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.begin.tlverilog</string>
							</dict>
						</dict>
						<key>end</key>
						<string>"</string>
						<key>endCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.end.tlverilog</string>
							</dict>
						</dict>
						<key>name</key>
						<string>string.quoted.double.tlverilog</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>\\.</string>
								<key>name</key>
								<string>constant.character.escape.tlverilog</string>
							</dict>
						</array>
					</dict>
					<dict>
						<key>begin</key>
						<string>'</string>
						<key>beginCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.begin.tlverilog</string>
							</dict>
						</dict>
						<key>end</key>
						<string>'</string>
						<key>endCaptures</key>
						<dict>
							<key>0</key>
							<dict>
								<key>name</key>
								<string>punctuation.definition.string.end.tlverilog</string>
							</dict>
						</dict>
						<key>name</key>
						<string>string.quoted.single.tlverilog</string>
						<key>patterns</key>
						<array>
							<dict>
								<key>match</key>
								<string>\\.</string>
								<key>name</key>
								<string>constant.character.escape.tlverilog</string>
							</dict>
						</array>
					</dict>
				</array>
			</dict>
		</dict>
		<key>scopeName</key>
		<string>source.tlverilog</string>
		<key>uuid</key>
		<string>789be04c-8b74-352e-8f37-63d336001277</string>
	</dict>
</plist>
